//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public short Status { get; set; }
        public Nullable<short> ProjectType { get; set; }
        public Nullable<decimal> LandArea { get; set; }
        public Nullable<short> AptrQty { get; set; }
        public Nullable<decimal> AptrRatioLand { get; set; }
        public Nullable<decimal> AptrRatioDev { get; set; }
        public Nullable<decimal> CarparkRatioLand { get; set; }
        public Nullable<decimal> CarparkRatioDev { get; set; }
    }
}
