//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.SupplierContactDetails = new HashSet<SupplierContactDetail>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ContactPerson1 { get; set; }
        public string ContactPerson2 { get; set; }
        public string ContactPerson3 { get; set; }
        public string ContactNo { get; set; }
    
        public virtual ICollection<SupplierContactDetail> SupplierContactDetails { get; set; }
    }
}
