//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierContactDetail
    {
        public int ContactID { get; set; }
        public int SupplierID { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
